# Generated by Django 5.0.4 on 2024-05-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_img.jpg', upload_to='profile_pic'),
        ),
    ]
