# Generated by Django 5.0.4 on 2024-05-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='test', max_length=1000),
        ),
    ]
